#cloud-config
users:
  - name: ansible
   groups: sudo
   shell: /bin/bash
   sudo: ['ALL=(ALL) NOPASSWD:ALL']
   ssh-authorized-keys:
     - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKwjW1XoEfU1b6krtqxBE11GK0HsgUd7kRKoug7z+ppU

disable_root: true
timezone: Europe/Moscow
repo_update: true
repo_upgrade: true

dnf:
  preserve_sources_list: true

packages:
  - wget
  - nano
  - java-11-openjdk

runcmd:
 - [sh, -c, "wget -P /tmp/ https://www.dropbox.com/s/udc91yvlx3lnlwy/elasticsearch-8.6.2-x86_64.rpm"]
 - [sh, -c, "wget -P /tmp/ https://www.dropbox.com/s/zfh0522d1r5m9s6/logstash-8.6.2-x86_64.rpm"]
 - [sh, -c, "rpm --install /tmp/elasticsearch-8.6.2-x86_64.rpm"]
 - [sh, -c, "rpm --install /tmp/logstash-8.6.2-x86_64.rpm"]
 - [sh, -c, "mv /etc/elasticsearch/elasticsearch.yml /etc/elasticsearch/elasticsearch.yml.bak"]
 - [sh, -c, "wget -P /etc/elasticsearch/ https://github.com/ta7575/sys-diplom/raw/main/elastic/elasticsearch.yml"]
 - [sh, -c, "wget -P /etc/logstash/conf.d/ https://github.com/ta7575/sys-diplom/raw/main/elastic/logstash/input.conf"]
 - [sh, -c, "wget -P /etc/logstash/conf.d/ https://github.com/ta7575/sys-diplom/raw/main/elastic/logstash/filter.conf"]
 - [sh, -c, "wget -P /etc/logstash/conf.d/ https://github.com/ta7575/sys-diplom/raw/main/elastic/logstash/output.conf"]
 - [sh, -c, "chmod 664 /etc/elasticsearch/elasticsearch.yml"]
 
 - [systemctl, daemon-reload]
 - [systemctl, enable, elasticsearch.service]
 - [systemctl, enable, logstash.service]
 - [systemctl, start, --no-block, elasticsearch.service]
 - [systemctl, start, --no-block, logstash.service]
