global:
  scrape_interval:     15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: "nodes"
    file_sd_configs:
    - files:
      - /etc/prometheus/sd_files/nodeexporter.yml
      refresh_interval: 1m

  - job_name: "nginx"
    scrape_interval: 15s
    static_configs:
      - targets: 
        - web1.srv:4040
        - web2.srv:4040
    
  
rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "localhost:9093"
