#cloud-config
users:
 - name: ansible
   groups: sudo
   shell: /bin/bash
   sudo: ['ALL=(ALL) NOPASSWD:ALL']
   ssh-authorized-keys:
     - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKwjW1XoEfU1b6krtqxBE11GK0HsgUd7kRKoug7z+ppU

disable_root: true
timezone: Europe/Moscow
repo_update: true
repo_upgrade: true

dnf:
  preserve_sourses_list: true

packages:
  - wget
  - nginx

runcmd:
 - [sh, -c, "wget -P /tmp/ https://github.com/martin-helmich/prometheus-nginxlog-exporter/releases/download/v1.10.0/prometheus-nginxlog-exporter_1.10.0_linux_amd64.rpm"]
 - [sh, -c, "sudo dnf -y install  /tmp/prometheus-nginxlog-exporter_1.10.0_linux_amd64.rpm"]
 - [sh, -c, "sudo wget -P /etc/systemd/system/ https://github.com/ta7575/sys-diplom/raw/main/config/prometheus-nginxlog-exporter.service"]
 - [sh, -c, "wget -P /etc/ https://github.com/ta7575/sys-diplom/raw/main/config/nginxlog_exporter.yml"]
 - [sh, -c, "wget -P /etc/systemd/system/ https://github.com/ta7575/sys-diplom/raw/main/config/node_exporter.service"]
 - [sh, -c, "wget -P /tmp/ https://github.com/prometheus/node_exporter/releases/download/v1.6.0/node_exporter-1.6.0.linux-amd64.tar.gz"]
 - [sh, -c, "tar xvf /tmp/node_exporter-1.6.0.linux-amd64.tar.gz"]
 - [sh, -c, "cp -r /node_exporter-1.6.0.linux-amd64/node_exporter /usr/local/bin"]
 - [sh, -c, "sudo useradd --no-create-home --shell /bin/false node_exporter"]
 - [sh, -c, "wget -P /tmp/  https://www.dropbox.com/s/dfmld6z73f83t7v/filebeat-8.6.2-x86_64.rpm"]
 - [sh, -c, "sudo dnf -y install  /tmp/filebeat-8.6.2-x86_64.rpm"]
 - [sh, -c, "mv /etc/filebeat/filebeat.yml /etc/filebeat/filebeat.yml.bak"]
 - [sh, -c, "wget -P /etc/filebeat https://github.com/ta7575/sys-diplom/raw/main/config/filebeat.yml"]
 
 - [systemctl, enable, filebeat.service]
 - [systemctl, enable, nginx.service]
 - [systemctl, start, --no-block, nginx.service]
 - [sh, -c, "echo 'Welcome to web server '$(hostname | cut -d '.' -f 1 ) > /usr/share/nginx/html/index.html"]
 - [systemctl, restart, nginx.service]
 - [systemctl, start, --no-block, node_exporter.service]
 - [systemctl, start, --no-block, prometheus-nginxlog-exporter.service]
 - [systemctl, start, --no-block, filebeat.service]
